name: Proyecto sesion5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar Python 3.10.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Instalar dependencias (pytest)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar tests
        run: pytest          
