name: projecte unitat 5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repositori checkout
        uses: actions/checkout@v2
      - name: Instalar Python 3.10.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Instalar dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar test
        run: |
          python -m unittest discover -s tests
